"""
Expansion Builder - Builds visually distinct markdown for Deep Research Expansion.

Based on: docs/authoritative/spec/GAPS_AND_BOOSTER_SPEC.md Part 2

The expansion section is appended to Doc 1 (Jump-Start Directions)
after a clear divider. It is visually distinct from the original content.
"""

from backend.models.booster_models import BoosterOutput


def build_booster_expansion_markdown(output: BoosterOutput) -> str:
    """
    Build visually distinct booster expansion section for Doc 1.

    This section is appended to Jump-Start directions after a divider.
    It contains DIRECTIONS only, not facts.

    Args:
        output: Booster output with directions

    Returns:
        Markdown string for the expansion section
    """
    lines = [
        "",
        "---",
        "",
        "## 🔍 Deep Research Expansion",
        f"*Generated by Deep Research Booster on {output.booster_timestamp[:10]}*",
        "",
        "> **Note:** These are research DIRECTIONS, not facts.",
        "> They suggest WHERE to look, not WHAT you'll find.",
        "",
    ]

    # Check if output is empty
    if output.is_empty():
        lines.extend([
            "### No Additional Directions",
            "",
            "The booster did not identify additional research directions.",
            "This may indicate the current sources provide comprehensive coverage,",
            "or that the identified gaps require domain-specific expertise to address.",
            "",
        ])
        return "\n".join(lines)

    # Missing Perspectives
    if output.missing_perspectives:
        lines.append("### Missing Perspectives to Seek")
        lines.append("")
        for mp in output.missing_perspectives:
            lines.append(f"**{mp.description}**")
            lines.append(f"- Why it matters: {mp.why_it_matters}")
            if mp.related_gaps:
                lines.append(f"- Related gaps: {', '.join(mp.related_gaps)}")
            lines.append("")

    # Primary Sources
    if output.primary_source_directions:
        lines.append("### Primary Sources to Find")
        lines.append("")
        lines.append("| Type | Description | Search Approach |")
        lines.append("|------|-------------|-----------------|")
        for psd in output.primary_source_directions:
            source_type = psd.source_type.value.replace("_", " ").title()
            # Escape pipe characters in content
            description = psd.description.replace("|", "\\|")
            search_suggestion = psd.search_suggestion.replace("|", "\\|")
            lines.append(f"| {source_type} | {description} | {search_suggestion} |")
        lines.append("")

    # Search Queries
    if output.suggested_search_queries:
        lines.append("### Suggested Search Queries")
        lines.append("")
        for i, sq in enumerate(output.suggested_search_queries, 1):
            lines.append(f"**{i}. `{sq.query}`**")
            lines.append(f"- Purpose: {sq.purpose}")
            lines.append(f"- Platform: {sq.platform_suggestion.value.title()}")
            if sq.related_gap:
                lines.append(f"- Addresses: {sq.related_gap}")
            lines.append("")

    # Research Questions
    if output.research_questions:
        lines.append("### Research Questions to Pursue")
        lines.append("")
        for rq in output.research_questions:
            lines.append(f"**{rq.question}**")
            lines.append(f"- Why: {rq.why_it_matters}")
            if rq.related_theme:
                lines.append(f"- Related to: {rq.related_theme}")
            lines.append("")

    # Footer
    lines.extend([
        "---",
        "",
        "*Deep Research Expansion complete.*",
        "*These are DIRECTIONS to explore, not established facts.*",
        "*Original source analysis appears above this section.*",
    ])

    return "\n".join(lines)


def build_booster_summary(output: BoosterOutput) -> dict:
    """
    Build a summary dict of booster output for API response.

    Args:
        output: Booster output

    Returns:
        Summary dictionary with counts
    """
    return {
        "perspectives_count": len(output.missing_perspectives),
        "source_directions_count": len(output.primary_source_directions),
        "queries_count": len(output.suggested_search_queries),
        "questions_count": len(output.research_questions),
        "total_directions": output.total_directions,
        "is_empty": output.is_empty(),
        "timestamp": output.booster_timestamp,
        "context_hash": output.context_bundle_hash,
    }
