"""Stage 11 — the production package, from the locked script and the registry.

Deterministic: everything here derives from artifacts that already exist
(script, registry, manifest), the ammo-cards way — claims ledger sorted by
confidence, per-beat cue cards carrying load-bearing facts and their anchors,
an asset checklist where the intake manifest's user-supplied material appears
as available assets and everything else is an explicit TODO rather than a
failure. Missing assets never block the package.
"""

import json
import re
from datetime import date
from pathlib import Path

from backend.lwm import ledger, manifest


def _beats(script: str) -> list[dict]:
    """Split the script into beats: movement/heading blocks, else paragraph runs."""
    parts = re.split(r"\n(?=#{1,3} )", script)
    if len(parts) > 1:
        beats = []
        for part in parts:
            lines = part.strip().splitlines()
            if not lines:
                continue
            title = lines[0].lstrip("# ").strip() if lines[0].startswith("#") else f"Beat {len(beats)+1}"
            beats.append({"title": title, "text": "\n".join(lines[1:]).strip() or lines[0]})
        return beats
    paras = [p.strip() for p in script.split("\n\n") if p.strip()]
    return [{"title": f"Beat {i+1}", "text": "\n".join(paras[i*4:(i+1)*4])}
            for i in range((len(paras) + 3) // 4)]


def _registry_rows(episode: Path) -> list[dict]:
    p = episode / "04-sources-registry.md"
    rows = []
    if not p.exists():
        return rows
    for line in p.read_text().splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.split("|")[1:-1]]
        if len(cells) == 9 and cells[0] not in ("#", "---"):
            rows.append(dict(zip(
                ("n", "claim", "class", "status", "source", "lb", "allowed", "prohibited", "anchor"),
                cells, strict=True)))
    return rows


def _overlap(a: str, b: str) -> int:
    from backend.pipeline.text_similarity import content_tokens
    return len(content_tokens(a) & content_tokens(b))


def build(episode: Path, script_path: Path) -> dict:
    script = script_path.read_text()
    rows = _registry_rows(episode)
    beats = _beats(script)
    data = manifest.load(episode)

    # Claims that actually appear in the script, by beat.
    for beat in beats:
        matched = sorted(rows, key=lambda r: -_overlap(r["claim"], beat["text"]))
        beat["claims"] = [r for r in matched if _overlap(r["claim"], beat["text"]) >= 4][:6]

    lb_rows = [r for r in rows if r.get("lb") == "y"]
    assets_available = [
        {"id": s["id"], "type": s["type"], "title": s.get("title"),
         "ref": s.get("canonical") or s.get("preserved_path"),
         "note": "user-supplied — candidate footage/reference" if s["type"] in ("youtube", "image", "file") else "reference"}
        for s in data["sources"]
    ]

    fc = episode / "10b-fact-check.json"
    fact_check = json.loads(fc.read_text()) if fc.exists() else None

    package = {
        "script": {"path": str(script_path), "words": len(script.split()),
                   "sha": __import__("hashlib").sha256(script.encode()).hexdigest()[:12]},
        "beats": [{"title": b["title"],
                   "cue_card": {
                       "load_bearing": [{"claim": r["claim"], "allowed": r["allowed"],
                                         "prohibited": r["prohibited"], "anchor": r["anchor"],
                                         "source": r["source"]}
                                        for r in b["claims"] if r.get("lb") == "y"],
                       "anchors": [r["anchor"] for r in b["claims"]
                                   if r.get("anchor") and r["anchor"] != "—"],
                   },
                   "visual_needs": [f"TODO — locate visual for: {b['title']}"],
                   "matched_assets": [a["id"] for a in assets_available
                                      if a["type"] in ("youtube", "image")]}
                  for b in beats],
        "claims_ledger": rows,
        "load_bearing": lb_rows,
        "assets": {"available": assets_available,
                   "missing": ["TODO — locate: archival footage / stills per beat (auto-discovery deferred)"]},
        "fact_check": ({"counts": fact_check["counts"],
                        "material_findings": fact_check["material_findings"]}
                       if fact_check else "not run"),
        "assembly": "governed by content-pipeline/PRODUCTION-ASSEMBLY-PIPELINE.md",
        "generated": str(date.today()),
    }

    (episode / "editing").mkdir(exist_ok=True)
    (episode / "editing" / "production-package.json").write_text(
        json.dumps(package, indent=1, ensure_ascii=False))
    (episode / "11-production-package.md").write_text(_render_md(package))
    ledger.update_row(episode, "11 production package", status="done",
                      notes=f"generated by lwm from {script_path.name} "
                            f"({package['script']['sha']}); {len(beats)} beats, "
                            f"{len(lb_rows)} load-bearing claims")
    return package


def _render_md(pkg: dict) -> str:
    out = [
        "<!--\nartifact:  11-production-package\nversion:   v1 (generated by lwm)\nreadiness: complete\n-->\n",
        "# Production package\n",
        f"Script: `{pkg['script']['path']}` · {pkg['script']['words']} words · version `{pkg['script']['sha']}`",
        f"Fact-check: {pkg['fact_check'] if isinstance(pkg['fact_check'], str) else 'run — ' + json.dumps(pkg['fact_check']['counts'])}",
        f"Assembly: {pkg['assembly']}\n",
        "## Cue / ammo cards — at the mic\n",
    ]
    for b in pkg["beats"]:
        out.append(f"### {b['title']}")
        for c in b["cue_card"]["load_bearing"]:
            out.append(f"- **LB** {c['claim']}\n  - say: {c['allowed'] or '—'} · never: {c['prohibited'] or '—'}"
                       f"\n  - anchor: {c['anchor']} · source: {c['source']}")
        if b["cue_card"]["anchors"]:
            out.append(f"- anchors in play: {' · '.join(b['cue_card']['anchors'])}")
        out.append(f"- visuals: {b['visual_needs'][0]}"
                   + (f" · candidate assets: {', '.join(b['matched_assets'])}" if b["matched_assets"] else ""))
        out.append("")
    out.append("## Asset inventory\n")
    for a in pkg["assets"]["available"]:
        out.append(f"- [{a['id']}] {a['type']}: {a['title'] or a['ref']} — {a['note']}")
    for m in pkg["assets"]["missing"]:
        out.append(f"- ⬜ {m}")
    out.append(f"\n## Claims ledger — {len(pkg['claims_ledger'])} rows, {len(pkg['load_bearing'])} load-bearing\n")
    out.append("Full table in `04-sources-registry.md`; machine copy in `editing/production-package.json`.")
    return "\n".join(out) + "\n"

