"""FastAPI application main module."""
from fastapi import FastAPI, HTTPException
from loguru import logger
from pydantic import BaseModel

from backend.config import get_settings
from backend.state import create_job, get_job
from backend.worker import run_research_job

settings = get_settings()

# Create FastAPI app
app = FastAPI(
    title="Research Agent API",
    description="Cloud-based research backend for aggregating content from multiple sources",
    version="0.1.0",
)


# Pydantic models
class CreateJobRequest(BaseModel):
    """Request model for creating a new research job."""
    topic: str
    # Later we will add: time_range, depth, source_types, etc.


class JobStatusResponse(BaseModel):
    """Response model for job status."""
    job_id: str
    topic: str
    status: str
    result: dict | None = None


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "ok",
        "environment": settings.environment,
    }


@app.post("/jobs", response_model=JobStatusResponse)
async def create_job_endpoint(request: CreateJobRequest):
    """
    Create a new research job.
    
    Args:
        request: Job creation request with topic
        
    Returns:
        Initial job status response
    """
    # Validate and clean topic
    topic = request.topic.strip()
    if not topic:
        raise HTTPException(status_code=400, detail="Topic cannot be empty")
    
    # Create job in Supabase (ID is generated by the database)
    job = create_job(topic=topic)
    
    # Enqueue Celery task
    logger.info(f"Enqueuing research job {job.job_id} for topic: {topic}")
    run_research_job.delay(job.job_id, topic)
    
    # Convert to response model
    return JobStatusResponse(
        job_id=job.job_id,
        topic=job.topic,
        status=job.status,
        result=job.result,
    )


@app.get("/jobs/{job_id}", response_model=JobStatusResponse)
async def get_job_status(job_id: str):
    """
    Get the status of a research job.
    
    Args:
        job_id: Unique identifier for the research job
        
    Returns:
        Job status response or 404 if not found
    """
    job = get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    
    return JobStatusResponse(
        job_id=job.job_id,
        topic=job.topic,
        status=job.status,
        result=job.result,
    )


