#!/usr/bin/env python3
"""Convert a Research Agent Briefing artifact (doc_2 JSON) into the writing
pipeline's stage-4b input file.

The v4 writing pipeline (RUNBOOK stage 4b, D-26) consumes the Briefing as a
markdown file named 04b-briefing.md in the episode folder. The RA already
emits the briefing in exactly that format — this script only unpacks the
JSON envelope: it writes the markdown with a short provenance header (job id,
gate results) and drops the HTML rendering alongside, since the HTML + Source
Vault pair is the surface Maz actually reads (D-025 visual spec).

Usage:
    python3 briefing_to_04b.py <packer_doc_2.json> <output_dir>

Writes into <output_dir>:
    04b-briefing.md    — stage 4b input (provenance header + briefing markdown)
    04b-briefing.html  — the reading surface, unchanged
"""

import json
import sys
from pathlib import Path


def gate_lines(gates: dict) -> list[str]:
    lines = []
    for name in ("coverage", "grounding"):
        g = gates.get(name)
        if not isinstance(g, dict):
            continue
        status = "PASS" if g.get("passed") else "FAIL"
        n_findings = len(g.get("findings", []))
        line = f"- {name} gate: {status} ({g.get('checked', '?')} checked"
        line += f", {n_findings} findings)" if n_findings else ")"
        lines.append(line)
    lint = gates.get("lint")
    if isinstance(lint, dict):
        status = "PASS" if lint.get("passes") else "FAIL"
        lines.append(
            f"- lint: {status} ({len(lint.get('errors', []))} errors, "
            f"{len(lint.get('advisories', []))} advisories)"
        )
    repairs = gates.get("grounding_repairs")
    if isinstance(repairs, dict) and repairs.get("ran"):
        lines.append(
            f"- grounding repairs: {len(repairs.get('applied', []))} applied, "
            f"{len(repairs.get('overruled', []))} overruled, "
            f"{len(repairs.get('unresolved', []))} unresolved"
        )
    return lines


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    doc = json.loads(src.read_text())
    data = doc["data"]
    meta = data.get("meta", {})
    gates = doc.get("gates", {})

    header = [
        "<!-- STAGE 4b BRIEFING — generated by the Research Agent, not hand-written.",
        f"     job: {data.get('job_id', 'unknown')}",
        f"     briefing version: {data.get('briefing_version', '?')} · "
        f"generated {meta.get('generated_on', '?')}",
        f"     {meta.get('source_count', '?')} sources "
        f"({meta.get('independent_source_count', '?')} independent) · "
        f"{meta.get('raw_words', '?')} raw words · "
        f"quotes verified {round(100 * meta.get('quote_verification_rate', 0))}% · "
        f"confidence {meta.get('confidence', '?')}",
        "     Gates at generation time:",
        *("     " + line for line in gate_lines(gates)),
        "     Canonical artifact = the structured JSON this file was unpacked from;",
        "     the HTML alongside is the reading surface. This markdown is the",
        "     pipeline-facing export (RUNBOOK 4b, D-26).",
        "-->",
        "",
    ]

    md_path = out_dir / "04b-briefing.md"
    md_path.write_text("\n".join(header) + doc["markdown"])
    print(f"wrote {md_path} ({md_path.stat().st_size} bytes)")

    html = doc.get("html")
    if html:
        html_path = out_dir / "04b-briefing.html"
        html_path.write_text(html)
        print(f"wrote {html_path} ({html_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
